### ISSUE TITLE
Doesn't work with OptionsetField in ss3.2.1

### ISSUE THREAD

**Issue by brasileric** [unclecheese/silverstripe-display-logic#44]
I see some updates for the OptionsetField about 20 days ago, but in ss3.2.1 (released 2 days ago) it's not working with OptionsetField yet. If I change the field type to dropdown or other it's working.

**Comment by unclecheese** [comment]
I just ran a test and didn't have any issues. When you say it doesn't work, are you trying to use the OptionSetField as a trigger or a toggleable field?

**Comment by hesteric** [comment]
Hi unclecheese,

Thanks for your response!

I don't know whate you mean with OptionSetField as trigger or toggleble, but this is the code:

    $unitsorpayfield = OptionsetField::create('UnitsOrPay', 'Which option do you prefer?', array(
                "1" => "Units",
                "2" => "Pay"
    ));
    $paymentfield = OptionsetField::create('Payment', 'Choose your pay method', $gateways);
    $paymentfield->displayIf("UnitsOrPay")->isEqualTo(2);

**Comment by brasileric** [comment]
If I use the DisplayLogicWrapper for this OptionSetField it works. So for me it's fixed now.

**Comment by unclecheese** [comment]
Nah, this is still an issue. You shouldn't have to do that. OptionsetField is just an oddity in a lot of ways and requires some special treatment. I'll look into getting a proper fix for this.

**Comment by michalkleiner** [comment]
Closing this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5

If the problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
